### ISSUE TITLE
Any whey to compare equivalence between two mig_networks?

### ISSUE THREAD

**Issue by renau** [lsils/mockturtle#109]
It would be good if once we have a mig_network or lut_network or... we can compare if two nets
are equivalent using the abcsat or other flows.

What is the easiest way to check equivalence in mockturtle?

**Comment by msoeken** [comment]
If the networks have not too many inputs (let's say up to 16), you can use `simulate` using `kitty::dynamic_truth_table` or `kitty::static_truth_table` and compare the resulting functions.

There is no SAT-based equivalence checking in *mockturtle*. We usually write the networks into a file (`write_verilog` or `write_bench`) and then check with ABC (`cec -n file1.v file2.v`).
