### ISSUE TITLE
cell_window.num_pis() vs. foreach_cell_fanin

### ISSUE THREAD

**Issue by marcelwa** [lsils/mockturtle#216]
Hello,

I'm trying to create a cell mapping for a network to process each cell. Please consider the following code snippet.

```c++
template<class Ntk>
void print_cell_io( Ntk const& ntk )   // ntk is a mapped network
{
  ntk.foreach_node( [&]( auto const n ) {
    if ( ntk.is_constant( n ) || ntk.is_pi( n ) || !ntk.is_cell_root( n ) )
      return;

    auto fanin_counter = 0u;
    ntk.foreach_cell_fanin( n, [&]( auto const f ) {
      ++fanin_counter;
    } );

    std::cout << "cell has " << fanin_counter << " fanins\n";

    auto cells = mockturtle::cell_window( ntk );
    cells.compute_window_for( n );
    std::cout << "cell_window i/o = " << cells.num_pis() << "/" << cells.num_pos() << "\n";
  } );
}
```

As I've understood the [documentation about mappings](https://mockturtle.readthedocs.io/en/latest/network.html?highlight=foreach_cell_fanin#mapping), a cell has a single root (i.e. one primary output?). So I assumed the `cell_fanin`s to be the primary inputs of the cell. When executing the above code in CirKit with e.g. AIG networks, the `cell_fanins` don't match the `cell_window` I/Os. Additionally, `cell_window`s can have multiple outputs.

May I ask you to clarify the difference between the cell mapping and the `cell_window` applied to it? How do I process cells correctly? How do I access their I/Os, their contained nodes, etc.?

Thanks a lot for your help!

**Comment by msoeken** [comment]
Hello,

Thanks for the question. The `cell_window` view is doing something different than you expect. Starting from some pivot node, which is a cell root, it creates a window around that node (bounded in size by some parameters) such that the window is covered itself by cells. So it does not cut through any cells. The motivation behind this is that you could throw away the current mapping of the window, remap it, and then insert it back into the original network without making the overall mapping inconsistent.

If you like to have a network structure around the cell than you can use `cut_view` instead.

I hope that this clarifies the problem.

**Comment by marcelwa** [comment]
Thanks for the quick response and the helpful comment! The `cut_view` does exactly what I want. Here is an updated version of the code above, just in case someone has the same question and comes across this issue:

```c++
template<class Ntk>
void print_cell_io( Ntk const& ntk ) // ntk is a mapped network
{
  ntk.foreach_node( [&]( auto const n ) {
    if ( ntk.is_constant( n ) || ntk.is_pi( n ) || !ntk.is_cell_root( n ) )
      return;

    std::vector<typename Ntk::node> leaves;
    ntk.foreach_cell_fanin( n, [&]( auto const f ) {
      leaves.push_back(f);
    } );

    std::cout << "cell has " << leaves.size() << " fanins\n";

    auto cut = mockturtle::cut_view(ntk, leaves, n);
    std::cout << "cut_view i/o = " << cut.num_pis() << "/" << cut.num_pos() << "\n";
  } );
}
```

Best regards!

**Comment by msoeken** [comment]
Thanks for providing the updated example!
