### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by marcelwa** [lsils/mockturtle#224]
Please have a look at the following piece of code which tries to synthesize an MIG network wrapped in a names_view from a truth table using akers_synthesis.

```c++
#include <mockturtle/networks/mig.hpp>
#include <mockturtle/views/names_view.hpp>
#include <mockturtle/algorithms/akers_synthesis.hpp>
#include <kitty/dynamic_truth_table.hpp>
#include <kitty/constructors.hpp>

int main()
{
    kitty::dynamic_truth_table tt(2);
    kitty::create_from_binary_string(tt, "0110");
    
    using named_mig = mockturtle::names_view<mockturtle::mig_network>;
    
    named_mig ntk;
    ntk = mockturtle::akers_synthesis<named_mig>(tt, tt);
}
```

I'm using a derivative of ubuntu 18.04 LTS and gcc/g++ 7.4.0. Trying to compile this code leads to the following error output.

```
./mockturtle/include/mockturtle/views/names_view.hpp:68:51: internal compiler error: in finish_member_declaration, at cp/semantics.c:3018
         current_pis.emplace_back( Ntk::make_signal( n ) );
                                   ~~~~~~~~~~~~~~~~^~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```

However, by combining declaration and definition of `ntk` in the code snippet above, it compiles and works just fine.

```c++
auto ntk = mockturtle::akers_synthesis<named_mig>(tt, tt);
```

Do you have any idea, what is going on here? Thanks a lot for your help!

**Comment by msoeken** [comment]
Thanks for pointing out this problem to use. I need to have a more detailed look to understand the root of the error, but I can already explain you why there is a difference.

In the first version that throws the error, you will initialise `ntk` using the copy constructor:

https://github.com/lsils/mockturtle/blob/master/include/mockturtle/views/names_view.hpp#L63

In the second version you are initialising using the constructor:

https://github.com/lsils/mockturtle/blob/master/include/mockturtle/views/names_view.hpp#L56

**Comment by marcelwa** [comment]
Sorry for being unclear in my formulation. I am aware that I'm using the copy assignment constructor vs the constructor in the respective cases. My question aimed more at the cause of the problem, i.e., why would they behave differently.

Thanks for looking into it. I really appreciate your effort!

**Comment by hriener** [comment]
Any progress on this issue? Maybe the GCC mailing list can help with this issue.

If no one objects I will mark the issue as resolved and close it soon.

**Comment by marcelwa** [comment]
I haven't further looked into the problem or what might have caused it. I avoided the copy assignment operator all together and was fine doing so. Just thought you should know about the bug's existence.

**Comment by hriener** [comment]
> I haven't further looked into the problem or what might have caused it. I avoided the copy assignment operator all together and was fine doing so. Just thought you should know about the bug's existence.

There is a chance that this has been addressed in your distribution or GCC directly.
