### ISSUE TITLE
Some C++17 compilers cannot compile this line:

### ISSUE THREAD

**Issue by DevelopDaily** [lsils/mockturtle#240]
https://github.com/lsils/mockturtle/blob/a7aaa39ceade8343b99933c98b0c7d8601867b53/include/mockturtle/networks/xmg.hpp#L326

It complains:

> error: non-constant-expression cannot be narrowed from type 'unsigned long long' to 'std::size_t' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]

**Comment by hriener** [comment]
Could you provide me with more details (information about the compiler) to reproduce this issue?

**Comment by hriener** [comment]
Closed because lack of participation.
