### ISSUE TITLE
Bug in node_map

### ISSUE THREAD

**Issue by lee30sonia** [lsils/mockturtle#260]
lines 258 and 281 should be` has( n )` and `has( ntk.get_node( f ) )`, respectively

**Comment by hriener** [comment]
Thanks, but I'm unable to follow. Which file?
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/utils/node_map.hpp#L258
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/utils/node_map.hpp#L281

**Comment by lee30sonia** [comment]
Sorry I forgot I added some functions so the line numbers are different at my side. It should be lines 244 and 267.

**Comment by hriener** [comment]
Thanks! Right, should be fixed!

**Comment by hriener** [comment]
Do you agree with the fix in PR #275?

**Comment by hriener** [comment]
It seems to be fixed! Thanks!
