### ISSUE TITLE
Bug in simulation.hpp

### ISSUE THREAD

**Issue by lee30sonia** [lsils/mockturtle#282]
All `node_to_value[f]` should be `node_to_value[ntk.get_node( f )]` (in lines 220, 349, and 353).
(Not sure if this really breaks something but just noticed it.)
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/simulation.hpp#L220

**Comment by hriener** [comment]
It seems that `node_map` is defined for `signal` and does the conversion internally, e.g.
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/utils/node_map.hpp#L254

Could you elaborate a bit on the details of the bug?

**Comment by lee30sonia** [comment]
Ah yes, I didn't notice that `node_map` implements both queries with `node` and with `signal`.
So it's line 301 that is kind of redundant 😛 
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/simulation.hpp#L301
