### ISSUE TITLE
incorrect description of fan in limit in reconvergence cut algo

### ISSUE THREAD

**Issue by mfernan2** [lsils/mockturtle#317]
include/mockturtle/algorithms/reconv_cut2.hpp contains the following:

```cpp
  /* \brief limit on the size of the supernode */
  int node_size_max;

  /* \brief limit on the size of the supernode */
  int node_fan_stop;
```

I think the comment on the second of these is meant to refer to a fan-in limit.

**Comment by hriener** [comment]
The comments stem from the original code in ABC and are in one-to-one correspondence to the variables there.

**Comment by mfernan2** [comment]
So it's intentional that these two differently named variables have an identical comment?

**Comment by hriener** [comment]
It's intentional that they are identical to the comments in ABC.
