### ISSUE TITLE
Assertion `_pend != _pcuts.end()' failed.

### ISSUE THREAD

**Issue by mfernan2** [lsils/mockturtle#371]
Hello, the latest esoteric issue from me...

I have some code that looks something like:

```cpp
mockturtle::cut_enumeration_params ps;
ps.cut_size = s;
ps.cut_limit = l;

const auto cuts = mockturtle::cut_enumeration<mockturtle::aig_network::node, true>(aig, ps);
```

I was using this with an `s` of `2` and `3`, which seemed to work fine with an `l` of `std::numeric_limits<decltype(ps.cut_limit)>::max()` (maybe already unwise...). However, when I go beyond `3` I get an assertion failure:

```
foo: /home/matthew/foo/mockturtle/include/mockturtle/algorithms/../utils/cuts.hpp:482: CutType& mockturtle::cut_set<CutType, MaxCuts>::add_cut(Iterator, Iterator) [with Iterator = unsigned int*; CutType = mockturtle::cut<16, mockturtle::cut_data<true, mockturtle::empty_cut_data> >; int MaxCuts = 26]: Assertion `_pend != _pcuts.end()' failed.
```

The default `cut_size` is `4` and the default `cut_limit` is `26`. I have confirmed that increasing either of these causes this assertion failure. I.e.:

```cpp
// this fails
ps.cut_size = 4;
ps.cut_limit = 27;

// so does this
ps.cut_size = 5;
ps.cut_limit = 26;
```

Possibly this is specific to my graph, but I suspect I am doing something wrong in my code. Are `4` and `26` somehow pseudo max values for these fields? I could not find anything in the documentation or comments to indicate this. I am using commit 1e7f423c08e69ee604c51892161d5280348a550e of mockturtle if this is relevant information.

**Comment by hriener** [comment]
Can you provide us with a simple example to reproduce the assertion violation on our side?

**Comment by mfernan2** [comment]
Yes, sorry, that would have been useful to include to begin with. I can't seem to reproduce this on a trivial example AIG. It reliably reproduces on two ~9000 variable AIGs, but they are both commercially sensitive files I can't easily share publicly. I'll try to distill one of these into a shareable example.

**Comment by hriener** [comment]
We have recently integrated more benchmarks (ISCAS, EPFL, IWLS) into mockturtle's experiment framework. Some of them are large and have many primary inputs. If one of these benchmarks triggers the same segmentation violation, we can use that benchmark to debug the issue and there is no need for sharing sensitive information.

**Comment by mfernan2** [comment]
Excellent suggestion. This is reproducible on the current head, 1fa274d0773a42145fc4610adb0b21b073abcaa7, using the first benchmark I tried, experiments/benchmarks/ac97_ctrl.aig. The code I'm using is the following:

```cpp
#include <cassert>
#include <cstdlib>
#include <limits>
#include <lorina/lorina.hpp>
#include <mockturtle/mockturtle.hpp>

int main(void) {

  // read in input file
  mockturtle::aig_network aig;
  lorina::return_code rc
    = lorina::read_aiger("ac97_ctrl.aig", mockturtle::aiger_reader(aig));
  assert(rc == lorina::return_code::success);

  // setup for enumerating 5-input cuts
  mockturtle::cut_enumeration_params ps;
  ps.cut_size = 5;
  ps.cut_limit = std::numeric_limits<decltype(ps.cut_limit)>::max();

  // setup cut enumeration
  const auto cuts
    = mockturtle::cut_enumeration<mockturtle::aig_network, true>(aig, ps);

  return 0;
}
```

My instinct is still that my usage of Mockturtle is somehow incorrect, so please let me know if there's a mistake in my code.

**Comment by hriener** [comment]
This line fixes the cut-set size at compile-time to 26 (regardless of your choice for `ps.cut_limit`):
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/cut_enumeration.hpp#L161

If you choose a value S larger than 25 for `ps.cut_limit`, you likely have to adjust the constant parameter `max_cut_num` to S+1.

Further, since `cut_set` stores an `std::array` with `max_cut_num` element, you may not want to increase it to a very large value:
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/utils/cuts.hpp#L460

**Comment by mfernan2** [comment]
Thanks, this explains some of the behavior I was seeing. I think I was mistaken in my original report that increasing `ps.cut_size` affects this. Now it seems I can only cause it by increasing `ps.cut_limit` as you describe.

This is enough to get my current use case working. Thanks! However, maybe `cut_enumeration` should reject any `cut_enumeration_params` with `cut_limit` greater than `max_cut_num`?

**Comment by hriener** [comment]
Fixes. Thanks!
