### ISSUE TITLE
AIG is being transformed when read in

### ISSUE THREAD

**Issue by mfernan2** [lsils/mockturtle#403]
I think maybe the following is caused by my own misunderstanding of mockturtle, but I'm not quite sure where I've gone wrong. When I read in an AIG and attempt to programmatically traverse it, it doesn't contain exactly the gates specified in the input AIG. The network seems to have been optimized before I get a chance to interact with it.

Distilling this to a simple AAG, I'm parsing the following:

```aag
aag 18 4 0 4 14
2
4
6
8
10
23
35
36
10 6 2
12 8 2
14 6 4
16 14 12
18 17 12
20 17 14
22 21 19
24 14 12
26 8 4
28 26 24
30 29 24
32 29 26
34 33 31
36 26 24
i0 a0
i1 a1
i2 b0
i3 b1
o0 Z0
o1 Z1
o2 Z2
o3 Z3
```

which is the following translated AIG: [small-circ.zip](https://github.com/lsils/mockturtle/files/5569951/small-circ.zip).

Using the C++ at the bottom of this post to view mockturtle's interpretation of this network, I get the following:

```sh
$ ./aigls small-circ.aig
aag 16 4 0 4 12
2
4
6
8
10
23
33
26
10 2 6
12 2 8
14 4 6
16 12 14
18 12 17
20 14 17
22 19 21
24 4 8
26 16 24
28 16 27
30 24 27
32 29 31
```

As you can see, it has fewer AND gates than the original. From node 12 onwards, it seems to have an altered understanding of the gates. Is this known behavior? Or maybe my input is somehow not canonical with respect to what mockturtle is assuming? If this is an issue with lorina rather than mockturtle, I can move it over there instead. Any help or advice would be greatly appreciated.

```cpp
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <lorina/aiger.hpp>
#include <mockturtle/mockturtle.hpp>

using net_t = mockturtle::aig_network;
using node_t = mockturtle::aig_network::node;
using signal_t = mockturtle::aig_network::signal;

int main(int argc, char **argv) {

  // validate command line arguments
  if (argc != 2 || strcmp(argv[1], "--help") == 0) {
    std::cerr << "usage: " << argv[0] << " aig_file\n"
              << " list Mockturtle's interpretation of an AIG\n";
    return EXIT_FAILURE;
  }

  // parse the input AIG into memory
  net_t aig;
  lorina::return_code rc
    = lorina::read_aiger(argv[1], mockturtle::aiger_reader(aig));
  if (rc != lorina::return_code::success) {
    std::cerr << "failed to parse " << argv[1] << "\n";
    return EXIT_FAILURE;
  }

  // print AAG header
  std::cout << "aag"
    << " " << (aig.num_pis() + aig.num_gates())
    << " " << aig.num_pis()
    << " 0" // latches (assume none)
    << " " << aig.num_pos()
    << " " << aig.num_gates()
    << "\n";

  // print inputs
  aig.foreach_pi([&](const node_t &n) {
    std::cout << (2 * aig.node_to_index(n)) << "\n";
  });

  // print outputs
  aig.foreach_po([&](const signal_t &s) {
    uint32_t index = aig.node_to_index(aig.get_node(s));
    uint32_t lsb = aig.is_complemented(s) ? 1 : 0;
    std::cout << (2 * index + lsb) << "\n";
  });

  // print gates
  aig.foreach_gate([&](const node_t &n) {
    std::cout << (2 * aig.node_to_index(n));
    aig.foreach_fanin(n, [&](const signal_t &s) {
      uint32_t index = aig.node_to_index(aig.get_node(s));
      uint32_t lsb = aig.is_complemented(s) ? 1 : 0;
      std::cout << " " << (2 * index + lsb);
    });
    std::cout << "\n";
  });

  return EXIT_SUCCESS;
}
```

**Comment by mfernan2** [comment]
I should have mentioned, this is using commit 1e7f423c08e69ee604c51892161d5280348a550e of mockturtle.

**Comment by hriener** [comment]
The input AIG is not "structurally hashed". The `create_and` method in the `aig_network` recognises that, e.g., the nodes 8 (literal 16) and 12 (literal 24) are identical and reuses the same node to represent them.

Note that, in our applications, we usually want the AIG to be structurally hashed.

A quick-and-dirty hack to disable structural hashing is to remove the lines 312 to 317 in the `create_and` method:
https://github.com/lsils/mockturtle/blob/master/include/mockturtle/networks/aig.hpp#L312

**Comment by mfernan2** [comment]
Ah yes, this is obvious now that you point it out. I should be able to avoid this kind of duplication prior to feeding input to mockturtle, which I think should make its idea of network match my input more closely. Thanks, Heinz!
