### ISSUE TITLE
Balancing (and probably other optimizations) don't preserve names

### ISSUE THREAD

**Issue by srtemp** [lsils/mockturtle#495]
We've run into an issue where, when optimizing a names_view, the names are not preserved through optimization. We've confirmed this is the case for balancing; it is likely true for other methods as well.
For example https://github.com/lsils/mockturtle/blob/260e29a8a3998400c88e9fd7360b29177ff82821/include/mockturtle/algorithms/balancing.hpp#L135
creates a new network (which may be a names_view), the rest of the function then populates the network but the names from the original network are never copied over.

**Comment by marcelwa** [comment]
I had the same issue, so I wrote this little snippet to help out. The original code is in [my repo fiction](https://github.com/marcelwa/fiction/blob/qcastack/include/fiction/algorithms/name_restoration.hpp). Maybe the mockturtle maintainers can comment on whether this would be a desired feature for a pull request.

```c++

#include <mockturtle/traits.hpp>
#include <mockturtle/utils/node_map.hpp>

template <typename NtkSrc, typename NtkDest>
void restore_network_name(const NtkSrc& ntk_src, NtkDest& ntk_dest) noexcept
{
    static_assert(mockturtle::is_network_type_v<NtkSrc>, "NtkSrc is not a network type");
    static_assert(mockturtle::is_network_type_v<NtkDest>, "NtkDest is not a network type");

    if constexpr (mockturtle::has_get_network_name_v<NtkSrc> && mockturtle::has_set_network_name_v<NtkDest>)
    {
        ntk_dest.set_network_name(ntk_src.get_network_name());
    }
}

template <typename NtkSrc, typename NtkDest>
void restore_names(const NtkSrc& ntk_src, NtkDest& ntk_dest,
                   mockturtle::node_map<mockturtle::signal<NtkDest>, NtkSrc>& old2new) noexcept
{
    restore_network_name(ntk_src, ntk_dest);

    if constexpr (mockturtle::has_has_name_v<NtkSrc> && mockturtle::has_get_name_v<NtkSrc> &&
                  mockturtle::has_set_name_v<NtkDest>)
    {
        static_assert(mockturtle::has_foreach_node_v<NtkSrc>, "NtkSrc does not implement the foreach_node function");
        static_assert(mockturtle::has_foreach_fanin_v<NtkSrc>, "NtkSrc does not implement the foreach_fanin function");
        static_assert(mockturtle::has_foreach_po_v<NtkSrc>, "NtkSrc does not implement the foreach_po function");
        static_assert(mockturtle::has_get_node_v<NtkSrc>, "NtkSrc does not implement the get_node function");

        const auto restore_signal_name = [&ntk_src, &ntk_dest, &old2new](const auto& f)
        {
            if (ntk_src.has_name(f))
            {
                auto name = ntk_src.get_name(f);

                ntk_dest.set_name(static_cast<mockturtle::node<NtkDest>>(old2new[ntk_src.get_node(f)]), name);
            }
        };

        const auto restore_output_name = [&ntk_src, &ntk_dest]([[maybe_unused]] const auto& po, const auto i)
        {
            if (ntk_src.has_output_name(i))
            {
                auto name = ntk_src.get_output_name(i);

                ntk_dest.set_output_name(i, name);
            }
        };

        ntk_src.foreach_node([&ntk_src, &restore_signal_name](const auto& n)
                             { ntk_src.foreach_fanin(n, restore_signal_name); });

        ntk_src.foreach_po(restore_output_name);
    }
}

```

**Comment by lee30sonia** [comment]
Hello,

Indeed, we do not/did not usually take care of the names when developing optimisation algorithms, as it is not needed for us. If this was to be implemented in a native way, line 145 in balancing, for example, should be modified as something like:
```c++
if constexpr ( has_has_name_v<Ntk> && has_get_name_v<Ntk> )
{
  if ( ntk_.has_name( n )
    old_to_new[n] = {dest.create_pi( ntk_.get_name( ntk_.make_signal( n ) ) ), 0u};
  else
    old_to_new[n] = {dest.create_pi(), 0u};
}
else
  old_to_new[n] = {dest.create_pi(), 0u};
```

Thanks @marcelwa for the patch! It would be great to have it integrated via a pull request. I think it is an easy fix without modifying every algorithm and it makes sense to have them as utility functions to be called optionally for users who need name preservation.

**Comment by marcelwa** [comment]
While the snippet can be provided as a utility function, it needs to be added to each algorithm individually still because the `node_map` is necessary to map the signals from one network to another.

**Comment by lee30sonia** [comment]
Yes. What I did another time was that I store the names in the very beginning, run various optimization/transformation algorithms without worrying about the names, and finally restore the names in the end. If the orders of PIs and POs stay the same, matching is not a problem.

So, there are various ways to achieve the same goal. As maintainers, we are happy to accept pull requests for individual algorithms to meet the needs of individual users, but we unfortunately do not have the bandwidth to check and fix every algorithms.

**Comment by srtemp** [comment]
Thanks @lee30sonia and @marcelwa,
That's a big help.  @yashton and I were planning to go through and add it to the algorithms we use, but wanted to make sure that there wasn't something in the works or a workaround we didn't know about.  We'll add a PR soon.

**Comment by lee30sonia** [comment]
Great! I'll close this issue then.
