### ISSUE TITLE
Resubstitution implementation

### ISSUE THREAD

**Issue by fmozafari** [lsils/mockturtle#498]
In the following line, shouldn't it be "set_visited"?
https://github.com/lsils/mockturtle/blob/fe7a1e9e471b112a3f7e465b25abe7c845e9ba84/include/mockturtle/algorithms/resubstitution.hpp#L322

**Comment by lee30sonia** [comment]
There are two fields in the data structure correlating to each node, the [visited flag](https://mockturtle.readthedocs.io/en/latest/network.html#visited-flags) and the [custom value](https://mockturtle.readthedocs.io/en/latest/network.html#custom-node-values). In this algorithm, the visited flags are used to mark visited nodes and the custom value fields are used to mark MFFC nodes.
