### ISSUE TITLE
Cut enumeration before and after node substitution in AIG

### ISSUE THREAD

**Issue by nitabukoshi** [lsils/mockturtle#526]
The issue is the following:
- The number of cuts is decreasing after node substitution in AIG.
- Node 21 (which has negated fanin 19 and negated fanin 20) is substituted with new node 54 (which has not negated fanin 19 and not negated fanin 20). 
- Attached are two pictures, one showing the AIG before substitution and the other after substituting node 21 with node 54. Also the terminal output showing the number of cuts before and after substitution.

Following is the code: 
```c++
#include <mockturtle/mockturtle.hpp>
using namespace std;
int main(int argc, char *argv[])
{ 
  //AIG from file 
  mockturtle::aig_network aig;
  lorina::read_aiger("file.aig", mockturtle::aiger_reader(aig));

  //Cut enumeration parameters
  mockturtle::cut_enumeration_params cp;
  cp.cut_size = 3u;   //maximum number of leaves
  cp.cut_limit = 100u; //maximum number of computed cuts for a node

  //Cut enumeration algorithm from mockturtle
  auto cuts = mockturtle::cut_enumeration<mockturtle::aig_network, true>(aig, cp);
  cout<<"Number of cuts: "<<cuts.total_cuts()<<"\n"; 

  //Node to be substituted, index 21
  int node_index = 21;

  auto old_node = aig.index_to_node(node_index);
  auto& old_node_storage = aig._storage->nodes[old_node];
  int child0 = aig._storage->nodes[node_index].children[0u].index;
  int child1 = aig._storage->nodes[node_index].children[1u].index;
  auto child0_sig = aig.make_signal(aig.index_to_node(child0));
  auto child1_sig = aig.make_signal(aig.index_to_node(child1));
 
  //The new node we want instead of the old node
  auto new_node = aig.create_and(child0_sig, child1_sig); 

  aig.substitute_node( old_node, new_node );  
  
  cout<<"\nNode substituted...\n";
  cleanup_dangling(aig);

  cuts = mockturtle::cut_enumeration<mockturtle::aig_network, true>(aig, cp);
  cout<<"\nNumber of cuts after substitution: "<<cuts.total_cuts()<<"\n";  
}
```

![Original AIG with node 21](https://user-images.githubusercontent.com/65900658/151991548-2d280403-78b2-407d-a115-436372de34a3.PNG)
![Substituted 21 to 54 AIG](https://user-images.githubusercontent.com/65900658/151991551-0a5643de-7fd0-44b5-843d-10f77b6a1bb2.PNG)
![terminal output](https://user-images.githubusercontent.com/65900658/151991935-4e204385-cc13-4e20-91cd-49d4a36c8a9b.PNG)

Thank you in advance for any help!

**Comment by hriener** [comment]
* I assume that you have manually adapted the maximum number of cuts supported by `cut_enumeration` because your `cut_limit=100` is clearly higher than `26`:
```
../include/mockturtle//algorithms/cut_enumeration.hpp:  static constexpr uint32_t max_cut_num = 26;
../include/mockturtle//algorithms/cut_enumeration.hpp:  using cut_set_t = cut_set<cut_t, max_cut_num>;
../include/mockturtle//algorithms/cut_enumeration.hpp:    assert( ps.cut_limit < cuts.max_cut_num && "cut_limit exceeds the compile-time limit for the maximum number of cuts" );
```
* To reproduce your issue, it would be practical to attach the AIG file.

**Comment by nitabukoshi** [comment]
- I had not changed the cut_limit before (in static constexpr uint32_t max_cut_num = 26). However, I just tried changing it to: static constexpr uint32_t max_cut_num = 100, and the result was the same as before.
- Attached is the AIG file.
[file.zip](https://github.com/lsils/mockturtle/files/7979816/file.zip)

**Comment by nitabukoshi** [comment]
- The cleanup_dangling call seems to have been the issue. I also changed the max_cut_num.

Thank you very much for your help!
