### ISSUE TITLE
Failing Windows builds using different toolsets (#530)

### ISSUE THREAD

**Issue by marcelwa** [lsils/mockturtle#531]
**Describe the bug**
When compiling with different toolsets under Windows, it becomes apparent that certain constructs do not compile.

**To Reproduce**
To be seen in #530.

**Environment**
 - OS: Windows
 - Compiler: Visual Studio 16 2019 with the v142 toolset
 - Compilation mode: RELEASE

**Additional context**
I suspect this to be the tip of the iceberg, unfortunately, as I had some further issues down the road when compiling any code involving `bill` under Windows with the v142 toolset. It would always complain that it misses `__sync_bool_compare_and_swap` in `glucose.hpp` (the actual solver). However, that will be a different issue. I would be glad to assist in the process of fixing these problems.

**Check list**
 * [X] I have tried to run in DEBUG mode and there was no assertion failure (or the reported bug is an assertion failure).
 * [X] I have made sure that the provided code ~~compiles~~ and reproduces the error.

**Comment by lee30sonia** [comment]
Thanks for reporting! I'm not an expert in Windows though, so this might be left open for some time...

**Comment by marcelwa** [comment]
I will gladly try to fix the arising issues. Are you okay with me pushing more commits to #530?

**Comment by lee30sonia** [comment]
Sure, thanks!

**Comment by marcelwa** [comment]
I've fixed the compilation errors in #530. However, I was still not able to reproduce the Glucose compilation error that I see, e.g., [here](https://github.com/marcelwa/fiction/runs/5181200852).

**Comment by hriener** [comment]
> I've fixed the compilation errors in #530. However, I was still not able to reproduce the Glucose compilation error that I see, e.g., [here](https://github.com/marcelwa/fiction/runs/5181200852).

- This seems to be a `bill` issue and should be reported there.
- `__sync_bool_compare_and_swap`, I believe, is a GCC intrinsic which isn't supported under this name on Windows platforms. However, the `vecThreads` class seems not to be used anywhere in our code. You could try to remove the class to see if `fiction` would then compile. (I would remove the code block from `#ifndef Glucose_VecThreads_h` to the corresponding `#endif`.)
- If removing the code part does not fix the issue, then have a look at what instantiates this template class.

**Comment by marcelwa** [comment]
Thank you for your helpful comment. I'll try that out!

**Comment by marcelwa** [comment]
I removed the `vecThreads` class as you recommended and it now works just fine as you can see [here](https://github.com/marcelwa/fiction/actions/runs/1875397027). Many thanks for the recommendation! I will port the changes to `bill` and create a PR there.
