### ISSUE TITLE
Using mockturtle as a library in another project

### ISSUE THREAD

**Issue by wei-shen-wang** [lsils/mockturtle#550]
I've seen the documentation and I did add the include directory of mockturtule to my include directory but just simply including mock turtule by `#include <mockturtle/mockturtle.hpp>` doesn't work because of the source code dependency on other library like "lorina".

**Comment by hriener** [comment]
Indeed, you have to satisfy the dependencies.

There are different approaches for this problem:
- You can cherry-pick the subset of the headers that you need. For example, if you have your own input interface and don't need `lorina`, then just don't copy the readers and the code that depends on the readers.
- `lorina` is header-only too. You should be able to copy the dependencies from the lib directory and add them to your project in the same way as you did for `mockturtle`.

You may run eventually into problems with libraries that are not header-only. If there are such dependencies currently included in `mockturtle`, then they are meant to be only temporary for some experimental features. In some cases, we were, however, not fast enough with cleaning them up. If you catch such a case, then we should fix that in `mockturtle`.
