### ISSUE TITLE
Bug in aqfp_flow_date

### ISSUE THREAD

**Issue by Flians** [lsils/mockturtle#595]
**Describe the bug**
When I run the aqfp_flow_date, I found that the cec result of the circuit `m3` was false.

**To Reproduce**
`./experiments/aqfp_flow_date`

**Environment**
 - OS: Ubuntu 22.04
 - Compiler: GCC 11.3.0
 - Compilation mode: RELEASE

**Additional context**
I have checked the code. I found that after `write_blif`, the primary output `y1` was changed from `~x0` to a constant.

**Comment by lee30sonia** [comment]
Close and replaced by #600.
