### ISSUE TITLE
Thank you, there is a problem, could you please help me. 

### ISSUE THREAD

**Issue by Bingo678** [lsils/mockturtle#611]
Thank you. May I ask, In your paper "Heuristic Logic Resynthesis Algorithms at the Core of Peephole Optimization", you mentioned that you integrated the proposed methods in the Mockturtle project. However, I could not find it in Mockturtle. Could you please tell me the specific project path?

**Comment by lee30sonia** [comment]
Hello, the heuristic resynthesis engines are in [`algorithms/resyn_engines`](https://github.com/lsils/mockturtle/tree/master/include/mockturtle/algorithms/resyn_engines). Specifically, the three algorithms described in the paper are `xag_resyn_decompose`, `mig_resyn_topdown`, and `mux_resyn`.
Note that these are the core resynthesis engines that are supposed to be combined in another high-level optimization algorithm, e.g., resubstitution, and are not designed to be used alone. Examples of how to compose them together are [`mig_resubstitution2`](https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/mig_resub.hpp#LL825C6-L825C25) and [`sim_resubstitution`](https://github.com/lsils/mockturtle/blob/master/include/mockturtle/algorithms/sim_resub.hpp#LL367C6-L367C24).

**Comment by Bingo678** [comment]
Thank you so much, it help me a lot, hope you have a nice day!




韩炳喆
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lsils/mockturtle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lsils/mockturtle] Thank you, there is a problem, could you please help me.  (Issue #611)





 
Hello, the heuristic resynthesis engines are in algorithms/resyn_engines. Specifically, the three algorithms described in the paper are xag_resyn_decompose, mig_resyn_topdown, and mux_resyn.
 Note that these are the core resynthesis engines that are supposed to be combined in another high-level optimization algorithm, e.g., resubstitution, and are not designed to be used alone. Examples of how to compose them together are mig_resubstitution2 and sim_resubstitution.
