### ISSUE TITLE
What if I want to use original ABC with mocktutle?

### ISSUE THREAD

**Issue by wjrforcyber** [lsils/mockturtle#619]
I integrate the original ABC in my project and at the same time would like to try mig in mockturtle, the problem is, the namespace seems have conflicts and mocktutle has some of the ABC function defined inside itself, I couldn't figure out how to deal with the conflict of the `abc` namespace and the `pabc` namespace.

Any easier way to integrate these two? I have checked [show case repo](https://github.com/lsils/lstools-showcase), but didn't find what I want.

**Comment by lee30sonia** [comment]
I haven't tried to do so before, but a colleague who did it some time ago mentioned that he had to change quite a lot of things to make it work. Unfortunately, we currently don't have a good solution for this.
If you do spend the time to make it work, please consider submitting a pull request so that we can merge the changes needed to do such a reasonable integration. Thank you!

**Comment by wjrforcyber** [comment]
> I haven't tried to do so before, but a colleague who did it some time ago mentioned that he had to change quite a lot of things to make it work. Unfortunately, we currently don't have a good solution for this.
> If you do spend the time to make it work, please consider submitting a pull request so that we can merge the changes needed to do such a reasonable integration. Thank you!

We have managed to do that with tons of Namespace changes which I myself really don't recommend...It would be better if mockturtle could use ABC as a whole lib or a binary like yosys does.

**Comment by lee30sonia** [comment]
We do not include the entire ABC package for a few reasons:
- Most importantly, we try to keep mockturtle a header-only library. Although this is not completely true now, it is still the goal. ABC has a lot of non-header code, and we had to make some changes (e.g. to inline functions) to make it header.
- Both ABC and mockturtle are being continuously developed. Including the entire codebase would require careful maintenance to keep track of the differences between versions and ensure compatibility.
