### ISSUE TITLE
sequential interface

### ISSUE THREAD

**Issue by whyrv** [lsils/mockturtle#63]
sequential interface is a good start. But to be useful, it should at least support an optional "clock" and a  "clock-enable".  then it becomes a tuple, not just a pair of ri,ro, i.e., each ro has a supporting set of inputs. It is upto the client to decide to use these or not.

**Comment by hriener** [comment]
The extensions in the PR are designed to support a specific use case.

Could you provide a more detailed example for your suggestions, e.g., in terms of pseudo code or a reference to an implementation (logic network package)?

**Comment by hriener** [comment]
Closed because lack of activity.
