### ISSUE TITLE
Inquiry Regarding Experimental Results in “Scalable Logic Rewriting Using Don’t Cares”

### ISSUE THREAD

**Issue by lzxdjb** [lsils/mockturtle#661]
I recently read your paper “Scalable Logic Rewriting Using Don’t Cares” and found the concept fascinating! However, I’m having some difficulty replicating the experimental results using the Mockturtle Library.

Could you please let me know which specific file or script I should run to reproduce the results shown in the paper? Any guidance would be greatly appreciated.

**Comment by aletempiac** [comment]
You can find the code to run the experiment here: https://github.com/aletempiac/mockturtle/blob/map_dont_cares/experiments/mig_flow.cpp
