### ISSUE TITLE
Name unnamed enum `emap_params.matching_mode`

### ISSUE THREAD

**Issue by dinoruic** [lsils/mockturtle#663]
The enum `emap_params.matching_mode` in `emap.hpp` is unnamed which makes it harder to reference it. It would be good if it were declared with a type name.

This is not urgent because we've worked around it using `decltype`.

**Comment by aletempiac** [comment]
Thank you for reporting! Let me know if the change in #665 is good enough.

**Comment by dinoruic** [comment]
Yes, that looks right! Thanks!
